services:
  geoserver:
    build:
      context: .
      dockerfile: Dockerfile.geoserver
    container_name: geoserver
    ports:
      - "8081:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_ADMIN_EMAIL=admin@example.com
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_LOG_LEVEL=INFO
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/gwc
      - GEOSERVER_LOG_LOCATION=/opt/geoserver/logs/geoserver.log
      - GEOWEBCACHE_LOG_LOCATION=/opt/geoserver/logs/gwc.log
      - GEOWEBCACHE_LOG_LEVEL=INFO
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - geoserver_logs:/opt/geoserver/logs
      - geoserver_gwc:/opt/geoserver/gwc
    restart: unless-stopped
    networks:
      - geograph_network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: geoserver_postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=geograph_layer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - geograph_network

volumes:
  geoserver_data:
  geoserver_logs:
  geoserver_gwc:
  postgres_data:

networks:
  geograph_network:
    driver: bridge

