services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
      tags:
        - geograph-web:dev-1.0.0
        - geograph-web:latest
    container_name: geograph_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    working_dir: /app
    restart: "no"
    networks:
      - geograph_network
    # command: sh -c "python -m venv /app/venv && . /app/venv/bin/activate && pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # command: sh -c ". /app/venv/bin/activate && pip install -r requirements.txt"
    command: sh -c ". /app/venv/bin/activate && python manage.py runserver 0.0.0.0:8000"

networks:
  geograph_network:
    external: false
