# Generated by Django 5.2.6 on 2025-09-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoImporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapefileimport',
            name='geoserver_layer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shapefileimport',
            name='geoserver_wfs_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shapefileimport',
            name='geoserver_wms_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shapefileimport',
            name='published_to_geoserver',
            field=models.BooleanField(default=False),
        ),
    ]
